name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ageorgeh/pnpm-action-setup@fix/skip-install-if-existing
        with:
          cache: true
          run_install: true
      - name: format
        run: |
          pnpm fmt:check
      - name: build
        run: |
          pnpm build
      # Disabled for now - lots of stuff in svelte files that ill deal with later
      # - name: eslint
      #   run: |
      #     # npx eslint .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ageorgeh/pnpm-action-setup@fix/skip-install-if-existing
        with:
          cache: true
          run_install: true
      - name: build
        run: |
          pnpm build
      - name: vitest
        run: |
          pnpm test
